# Generated by Django 2.2.7 on 2019-12-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('title', models.CharField(max_length=25)),
                ('inn', models.IntegerField(default=0)),
                ('telefon', models.IntegerField(default=0)),
                ('pred', models.BooleanField(default=False)),
                ('postav', models.BooleanField(default=False)),
                ('gruz', models.BooleanField(default=False)),
            ],
        ),
    ]
