# Generated by Django 2.2.7 on 2019-12-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gruz',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='person',
            name='inn',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='postav',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='person',
            name='pred',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='person',
            name='telefon',
            field=models.IntegerField(),
        ),
    ]
