# Generated by Django 2.2.7 on 2019-12-01 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ip_app', '0002_auto_20191201_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='gruz',
            new_name='selector',
        ),
        migrations.RemoveField(
            model_name='person',
            name='postav',
        ),
        migrations.RemoveField(
            model_name='person',
            name='pred',
        ),
    ]
